# Generated by Django 3.2.2 on 2022-10-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
