# Generated by Django 4.1.2 on 2022-11-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_alter_report_graphurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='graphURL',
            field=models.CharField(max_length=500),
        ),
    ]
