# Generated by Django 3.2.2 on 2022-10-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_member_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
