# Generated by Django 3.2.2 on 2022-10-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
