# Generated by Django 3.2.2 on 2022-10-06 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_member_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='image',
            new_name='member_image',
        ),
    ]
