# Generated by Django 3.2.2 on 2022-10-21 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Research.project')),
            ],
        ),
    ]
