# Generated by Django 3.2.2 on 2022-10-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='outreach/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
