# Generated by Django 3.2.2 on 2022-10-21 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0004_paper_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='date',
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 21, 13, 31, 22, 200588)),
        ),
    ]
