# Generated by Django 3.2.2 on 2022-10-21 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0005_auto_20221021_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 21, 14, 6, 49, 548018)),
        ),
    ]
