# Generated by Django 4.1.2 on 2022-10-29 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0007_auto_20221021_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 29, 9, 46, 32, 506881)),
        ),
    ]
