# Generated by Django 4.1.2 on 2024-01-08 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0018_alter_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 1, 2, 51, 798498)),
        ),
    ]
