# Generated by Django 3.2.2 on 2022-10-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/')),
                ('name', models.CharField(max_length=250)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
