# Generated by Django 3.2.2 on 2022-10-15 13:35

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nsdr_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Audio')),
                ('name', models.CharField(max_length=250)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nsdr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Script.nsdr_type')),
            ],
        ),
    ]
