# Generated by Django 3.2.2 on 2022-10-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='nsdr',
        ),
        migrations.AddField(
            model_name='script',
            name='nsdr_type',
            field=models.CharField(default='NSDR', max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='nsdr_type',
        ),
    ]
