# Generated by Django 3.2.2 on 2022-10-14 08:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='audio',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Audio'),
        ),
    ]
