# Generated by Django 4.1.2 on 2022-10-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='NSDRType',
            new_name='Type',
        ),
    ]
