# Generated by Django 4.1.2 on 2022-10-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nsdr_type',
            new_name='nsdr',
        ),
    ]
