# Generated by Django 3.2.2 on 2022-10-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0002_auto_20221015_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='nsdr_type',
        ),
    ]
