# Generated by Django 4.1.2 on 2022-10-20 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0002_nsdr_type_script_nsdrtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='nsdrType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Script.nsdr_type'),
        ),
    ]
