# Generated by Django 4.1.2 on 2022-10-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0003_alter_script_nsdrtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='nsdrType',
        ),
    ]
